from .guidance import *
from .studentorg import *
from .scholarship import *
from .job_placement import *
from .medical import *
from .student_life import *
from .alumni import *
from .discipline import *
from .main import *