from django.urls import path
from mainpage.views.alumni import (
    idRequest,
    search_id,
    add_alumni,
    search_id2,
    graduateTracer_submit,
    graduateTracer,
    alumni_events,
    jobfairs,
    yearbook,
    search_yearbook,
    transaction_alumni,
    transac_search,
    admin_id_request,
    approve_alumni_request,
    claim_alumni_id,
    admin_gradTracer,
    admin_events,
    admin_jobfairs,
    alumni_events_admin,update_form_status,admin_tracer_list

)

urlpatterns = [
    path('admin_grad_tracer/', admin_tracer_list, name='admin_tracer_list'),
    path('update-form-status/<str:pk>/', update_form_status, name='update_form_status'),
    path("id_request/", idRequest, name="idRequest"),
    path("search_id/", search_id, name="search_id"),
    path("add_alumni/", add_alumni, name="add_alumni"),
    path("search_id2/", search_id2, name="search_id2"),
    path("graduateTracer_submit", graduateTracer_submit, name="graduateTracer_submit"),
    path("graduateTracer/", graduateTracer, name="graduateTracer"),
    path("reunionandevents/", alumni_events, name="alumni_events"),
    path("alumni_events_admin/", alumni_events_admin, name="alumni_events_admin"),
    path("jobfairs/", jobfairs, name="jobfairs"),
    path("yearbook/", yearbook, name="yearbook"),
    path("search_yearbook/", search_yearbook, name="search_yearbook"),
    path("transaction_alumni.html/", transaction_alumni, name="transaction_alumni"),
    path("transac_search", transac_search, name="transac_search"),
    path("admin_id_request/", admin_id_request, name="admin_idRequest"),
    path("approve_alumni_request/<int:alumni_id>/", approve_alumni_request, name="approve_alumni_request"),
    path("claim_alumni_id/<int:alumni_id>/", claim_alumni_id, name="claim_alumni_id"),
    path("admin_grad_tracer/", admin_gradTracer, name="admin_gradTracer"),
    path("admin_events/", admin_events, name="admin_events"),
    path("admin_jobfairs", admin_jobfairs, name="admin_jobfairs"),
]