# Generated by Django 5.0.2 on 2025-08-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseprofile',
            name='course_year',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='date_of_incident',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='witnesses',
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='community_service_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='custom_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='custom_offense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
      migrations.AddField(
    model_name='caseprofile',
    name='date_reported',
    field=models.DateField(auto_now_add=True),
),
        migrations.AddField(
            model_name='caseprofile',
            name='suspension_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='action_taken',
            field=models.CharField(choices=[('Community Service', 'Community Service'), ('Suspension', 'Suspension'), ('Warning', 'Warning'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='offense_type',
            field=models.CharField(choices=[('Bullying', 'Bullying'), ('Cheating', 'Cheating'), ('Vandalism', 'Vandalism'), ('Others', 'Others')], max_length=50),
        ),
    ]
