# Generated by Django 5.0.2 on 2025-08-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseprofile',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='caseprofile',
            name='student_name',
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo'),
            preserve_default=False,
        ),
    ]
