# Generated by Django 5.0.2 on 2025-06-12 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidationCoScho',
            fields=[
                ('dv_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dv_date', models.DateField()),
                ('total_admin_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_stipend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('office_supplies', models.DecimalField(decimal_places=2, max_digits=10)),
                ('communication', models.DecimalField(decimal_places=2, max_digits=10)),
                ('traveling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('representation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professional_services', models.DecimalField(decimal_places=2, max_digits=10)),
                ('legal_services', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationTDP',
            fields=[
                ('date', models.DateField()),
                ('check_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('particulars', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=1, null=True)),
                ('academic_year', models.CharField(max_length=9, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('liquidation_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_disbursement', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationTES',
            fields=[
                ('date', models.DateField()),
                ('check_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('particulars', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=1, null=True)),
                ('academic_year', models.CharField(max_length=9, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('liquidation_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_disbursement', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='extension',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='zip_code',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='contact',
            field=models.CharField(default='N/A', max_length=11),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='emailadd',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=50)),
                ('requesting', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_file', models.FileField(blank=True, null=True, upload_to='applicants/cor_pic/')),
                ('grade_file', models.FileField(blank=True, null=True, upload_to='applicants/grade_pic/')),
                ('schoolid_file', models.FileField(blank=True, null=True, upload_to='applicants/schoolid_pic/')),
                ('scholar_type', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('studID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='scholars',
            fields=[
                ('scholar_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('scholar_type', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10, null=True)),
                ('scholar_status', models.CharField(default='ACTIVE', max_length=10)),
                ('studID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('scholar_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gpa', models.FloatField()),
                ('cor_file', models.FileField(blank=True, null=True, upload_to='scholar_requirements/cor_files/')),
                ('grade_file', models.FileField(blank=True, null=True, upload_to='scholar_requirements/grade_files/')),
                ('schoolid_file', models.FileField(blank=True, null=True, upload_to='scholar_requirements/schoolid_files/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('units', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('record', models.CharField(default='NEW', max_length=10)),
                ('studID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo')),
                ('scholar_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.scholars')),
            ],
        ),
        migrations.CreateModel(
            name='tdpDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('disbursement_number', models.CharField(blank=True, max_length=50, null=True)),
                ('disbursement_particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('disbursement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdpdisbursements', to='mainpage.liquidationtdp')),
            ],
        ),
        migrations.CreateModel(
            name='tesDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('disbursement_number', models.CharField(blank=True, max_length=50, null=True)),
                ('disbursement_particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('disbursement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='mainpage.liquidationtes')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('gpa', models.FloatField()),
                ('scholar_status', models.CharField(default='ACTIVE', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=10, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('total_units_enrolled', models.IntegerField(null=True)),
                ('scholar_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_details', to='mainpage.scholars')),
            ],
            options={
                'unique_together': {('scholar_ID', 'year', 'semester')},
            },
        ),
    ]
