# Generated by Django 5.0.2 on 2025-07-22 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_communityservicetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinarySanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction', models.CharField(choices=[('apology_letter', 'Apology Letter'), ('community_service', 'Community Service'), ('suspension', 'Suspension'), ('apology_letter_community_service', 'Apology Letter and Community Service'), ('expulsion', 'Expulsion')], max_length=50)),
                ('sanction_completed', models.BooleanField(default=False)),
                ('apology_letter', models.FileField(blank=True, null=True, upload_to='apology_letters/')),
                ('community_service_hours', models.IntegerField(blank=True, null=True)),
                ('community_service_deadline', models.DateField(blank=True, null=True)),
                ('suspension_start_date', models.DateField(blank=True, null=True)),
                ('suspension_end_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo')),
            ],
        ),
    ]
