# Generated by Django 5.0.2 on 2025-08-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_caseprofile_student_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='communityservicetracker',
            old_name='service_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='student_signature',
        ),
    ]
