# Generated by Django 5.0.2 on 2025-08-20 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_caseprofile_course_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='date_reported',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
