# Generated by Django 5.0.2 on 2025-08-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='student',
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.caseprofile'),
            preserve_default=False,
        ),
    ]
