# Generated by Django 5.2.1 on 2025-09-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=150)),
                ('donation_type', models.CharField(max_length=10)),
                ('gcash_number', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_card', models.CharField(blank=True, max_length=20, null=True)),
                ('image_details', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('what_kind', models.CharField(blank=True, max_length=20, null=True)),
                ('recepient', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('recepient_things', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=11, null=True)),
                ('date_sched', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('image_upload', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('image_upload', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='QrDonation',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('gcash', models.ImageField(upload_to='images/')),
                ('bpi', models.ImageField(upload_to='images/')),
                ('bdo', models.ImageField(upload_to='images/')),
                ('landbank', models.ImageField(upload_to='images/')),
                ('pnb', models.ImageField(upload_to='images/')),
                ('metro', models.ImageField(upload_to='images/')),
                ('union', models.ImageField(upload_to='images/')),
                ('china', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
