# Generated by Django 5.0.2 on 2025-08-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_caseprofile_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='action_taken',
            field=models.CharField(choices=[('Community Service', 'Community Service'), ('Suspension', 'Suspension'), ('Counseling', 'Counseling'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='offense_type',
            field=models.CharField(choices=[('Bullying', 'Bullying'), ('Cheating', 'Cheating'), ('Others', 'Others')], max_length=50),
        ),
    ]
