# Generated by Django 5.0.2 on 2025-07-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_disciplinarysanction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='id',
        ),
        migrations.AddField(
            model_name='applicants',
            name='application_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
