# Generated by Django 5.0.2 on 2025-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_communityservicetracker_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='time_out',
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='afternoon_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='afternoon_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='morning_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='morning_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
