# Generated by Django 5.2.1 on 2025-09-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_mod_program_projects_qrdonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='programid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
