# Generated by Django 5.0.2 on 2025-07-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_applicants_id_applicants_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateform',
            name='enrollmentdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='pursuingstudies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='studiesAddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='studiesdegree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='universityinstitution',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
