# Generated by Django 5.0.2 on 2025-08-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_ppmpdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmpdocument',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
