# Generated by Django 5.2.1 on 2025-09-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_programimage_programs_delete_program_delete_projects_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
