# Generated by Django 5.0.2 on 2025-08-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_ppmpdocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppmpdocument',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
