# Generated by Django 5.2.1 on 2025-09-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_rename_programs_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programimage',
            old_name='project',
            new_name='program',
        ),
    ]
