# Generated by Django 5.2.1 on 2025-09-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_crowdfundingproject_donation_donationchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfundingproject',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
