# Generated by Django 5.2.1 on 2025-09-20 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_crowdfundingproject_goal_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdfundingproject',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='crowdfundingproject',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='crowdfundingproject',
            name='goal_amount',
        ),
        migrations.RemoveField(
            model_name='donationchannel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donationchannel',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='crowdfundingproject',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationchannel',
            name='imageCrowdfunding',
            field=models.ImageField(default=1, upload_to='imageCrowdfunding/'),
            preserve_default=False,
        ),
    ]
