# Generated by Django 5.2.1 on 2025-09-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_remove_crowdfundingproject_current_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffInfo',
            fields=[
                ('staffID', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('emailadd', models.EmailField(default='N/A', max_length=254)),
                ('contact', models.CharField(default='N/A', max_length=11)),
                ('extension', models.CharField(default='N/A', max_length=10)),
                ('zip_code', models.CharField(default='N/A', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
