# Generated by Django 5.2.1 on 2025-10-01 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_staffinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='mainpage.organization'),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
