# Generated by Django 5.2.1 on 2025-10-01 06:55

import django.utils.timezone
import mainpage.models.studentorg
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_alter_accreditation_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='accomplishment_report',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='bank_passbook',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='calendar_of_activities',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='certificate_of_registration',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='faculty_adviser_appointment',
            field=models.FileField(default=django.utils.timezone.now, upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='financial_statement',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='inventory_of_properties',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='letter_of_intent',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='list_of_members',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='list_of_officers',
            field=models.FileField(default=django.utils.timezone.now, upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='organization_bylaws',
            field=models.FileField(default=django.utils.timezone.now, upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='other_documents',
            field=models.FileField(default='hello.png', upload_to='accreditation/', validators=[mainpage.models.studentorg.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='AccreditationDocument',
        ),
    ]
