# Generated by Django 5.2.1 on 2025-10-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_accreditation_accomplishment_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinfo',
            name='zip_code',
        ),
    ]
