# Generated by Django 5.2.1 on 2025-10-12 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_remove_staffinfo_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityservicetracker',
            old_name='date',
            new_name='service_date',
        ),
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='afternoon_in',
        ),
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='afternoon_out',
        ),
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='morning_in',
        ),
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='morning_out',
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='student_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='time_in',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityservicetracker',
            name='time_out',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('guard', 'Guard'), ('org_member', 'Org Member'), ('guidance', 'Guidance'), ('student', 'Student')], max_length=20),
        ),
    ]
