# Generated by Django 5.2.1 on 2025-10-18 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_rename_date_communityservicetracker_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityservicetracker',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communityservicetracker',
            name='remarks',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communityservicetracker',
            name='student_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
