# Generated by Django 5.2.1 on 2025-10-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_communityservicetracker_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='student',
        ),
    ]
