# Generated by Django 5.2.1 on 2025-10-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_remove_communityservicetracker_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityservicetracker',
            options={'ordering': ['-service_date']},
        ),
    ]
