# Generated by Django 5.2.1 on 2025-10-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_alter_communityservicetracker_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityservicetracker',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning (7 AM - 1 PM)'), ('afternoon', 'Afternoon (12 PM - 6 PM)')], default='morning', max_length=10),
            preserve_default=False,
        ),
    ]
