# Generated by Django 5.2.1 on 2025-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_communityservicetracker_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityservicetracker',
            options={},
        ),
        migrations.AlterField(
            model_name='communityservicetracker',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='communityservicetracker',
            unique_together={('case', 'service_date', 'session')},
        ),
    ]
