# Generated by Django 5.2.1 on 2025-10-21 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_alter_communityservicetracker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo'),
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo'),
        ),
        migrations.AlterField(
            model_name='medicalrequirement',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo'),
        ),
        migrations.AlterField(
            model_name='facultyrequest',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.staffinfo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.studentinfo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
