# Generated by Django 5.2.1 on 2025-10-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0022_alter_patientrequest_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrecord',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrecord',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10, null=True),
        ),
    ]
