# Generated by Django 5.2.1 on 2025-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0023_prescriptionrecord_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('clinic_admin', 'Clinic Admin'), ('guidance', 'Guidance'), ('org_admin', 'Org Admin'), ('guard', 'Guard'), ('student', 'Student'), ('staff', 'Staff'), ('discipline_officer', 'Discipline Officer'), ('alumni_officer', 'Alumni Officer'), ('student_life_staff', 'Student Life Staff')], max_length=20),
        ),
    ]
