# Generated by Django 5.2.1 on 2025-10-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0024_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtassessment',
            name='dateAccepted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
