# Generated by Django 5.2.1 on 2025-10-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0025_alter_ojtassessment_dateaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateform',
            name='organizationType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
