# Generated by Django 5.2.1 on 2025-10-25 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0027_alter_individualprofilebasicinfo_yearlvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofilebasicinfo',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g., 09171234567 or +639171234567).', regex='^(09|\\+639)\\d{9}$')]),
        ),
    ]
