# Generated by Django 5.2.1 on 2025-10-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0028_alter_individualprofilebasicinfo_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityservicetracker',
            name='student_signature',
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='offense_number',
            field=models.CharField(choices=[('1st', '1st Offense'), ('2nd', '2nd Offense'), ('3rd', '3rd Offense'), ('4th', '4th Offense'), ('5th', '5th Offense'), ('Subsequent', 'Subsequent Offense (Beyond 5th)')], default='1st', max_length=10),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='action_taken',
            field=models.CharField(choices=[('Oral Reprimand', 'Oral Reprimand'), ('Written Reprimand', 'Written Reprimand'), ('Community Service', 'Community Service'), ('Suspension', 'Suspension'), ('Expulsion', 'Expulsion'), ('Counseling', 'Counseling/Intervention'), ('Others', 'Other Action/Penalty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='offense_type',
            field=models.CharField(choices=[('Bullying', 'Bullying/Harassment'), ('Cheating', 'Academic Dishonesty (Cheating/Plagiarism)'), ('Uniform/ID Violation', 'Uniform/ID Violation'), ('Class Disruption', 'Class or Academic Activity Disruption'), ('Drug/Alcohol Use', 'Drug or Alcohol Possession/Use'), ('Theft/Vandalism', 'Theft or Vandalism'), ('Immorality/Lewdness', 'Immorality or Lewd Acts'), ('Deadly Weapon', 'Possession of Deadly Weapon'), ('Hazing', 'Hazing or Initiation Rites'), ('Falsification', 'Falsification of Documents'), ('Unauthorized Use', 'Unauthorized Activity/Collection'), ('Others', 'Other Offense')], max_length=50),
        ),
    ]
