# Generated by Django 5.2.1 on 2025-10-25 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0029_remove_communityservicetracker_student_signature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseprofile',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Case Profile', 'verbose_name_plural': 'Case Profiles'},
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of Incident'),
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='discipline_evidence/', verbose_name='Supporting Evidence (Attachment)'),
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reported By (User ID/Name)'),
        ),
        migrations.AddField(
            model_name='caseprofile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved/Closed')], default='Pending', max_length=20, verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='action_taken',
            field=models.CharField(choices=[('Oral Reprimand', 'Oral Reprimand'), ('Written Reprimand', 'Written Reprimand'), ('Community Service', 'Community Service'), ('Suspension', 'Suspension'), ('Expulsion', 'Expulsion'), ('Counseling', 'Counseling/Intervention'), ('Others', 'Other Action/Penalty')], max_length=50, verbose_name='Action Taken'),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='community_service_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Community Service Hours'),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='custom_action',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specify Custom Action'),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='custom_offense',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specify Custom Offense'),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='date_reported',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='offense_number',
            field=models.CharField(choices=[('1st', '1st Offense'), ('2nd', '2nd Offense'), ('3rd', '3rd Offense'), ('4th', '4th Offense'), ('5th', '5th Offense'), ('Subsequent', 'Subsequent Offense (Beyond 5th)')], default='1st', max_length=10, verbose_name='Offense Number'),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='offense_type',
            field=models.CharField(choices=[('Bullying', 'Bullying/Harassment'), ('Cheating', 'Academic Dishonesty (Cheating/Plagiarism)'), ('Uniform/ID Violation', 'Uniform/ID Violation'), ('Class Disruption', 'Class or Academic Activity Disruption'), ('Drug/Alcohol Use', 'Drug or Alcohol Possession/Use'), ('Theft/Vandalism', 'Theft or Vandalism'), ('Immorality/Lewdness', 'Immorality or Lewd Acts'), ('Deadly Weapon', 'Possession of Deadly Weapon'), ('Hazing', 'Hazing or Initiation Rites'), ('Falsification', 'Falsification of Documents'), ('Unauthorized Use', 'Unauthorized Activity/Collection'), ('Others', 'Other Offense')], max_length=50, verbose_name='Offense Type'),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='suspension_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Suspension Duration (e.g., "5 days")'),
        ),
    ]
