# Generated by Django 5.2.1 on 2025-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0030_alter_caseprofile_options_caseprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Graduated', 'Graduated'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred')], default='Enrolled', max_length=20),
        ),
    ]
