# Generated by Django 5.2.1 on 2025-10-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0031_studentinfo_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='alumniaddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='alumnibirthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='alumnicontact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='alumnidate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email_add',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='parentguardian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='sssgsis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
