# Generated by Django 5.2.1 on 2025-10-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0032_alter_alumni_alumniaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateform',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True),
        ),
    ]
