# Generated by Django 5.2.1 on 2025-10-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0033_graduateform_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdfundingproject',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='qrdonation',
            name='qr_id',
        ),
        migrations.AddField(
            model_name='donationchannel',
            name='name',
            field=models.CharField(default='Payment Channel', max_length=100),
        ),
        migrations.AddField(
            model_name='qrdonation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
