# Generated by Django 5.2.1 on 2025-10-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0034_remove_crowdfundingproject_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_statements', to='mainpage.organization'),
        ),
    ]
