# Generated by Django 5.2.1 on 2025-10-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0035_alter_financialstatement_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='course',
            field=models.CharField(max_length=50),
        ),
    ]
