# Generated by Django 5.2.1 on 2025-10-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0036_alter_officer_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='officer_profiles/'),
        ),
    ]
