# Generated by Django 5.2.1 on 2025-10-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0037_officer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default='2025-11-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default='2025-11-01'),
            preserve_default=False,
        ),
    ]
