# Generated by Django 5.2.1 on 2025-11-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0038_remove_schedule_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this adviser currently active in their role?'),
        ),
    ]
