# Generated by Django 5.2.1 on 2025-11-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0039_adviser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='adviser',
            name='date_deactivated',
            field=models.DateField(blank=True, help_text='The date the adviser was set to inactive. If blank, they are active.', null=True, verbose_name='Date Deactivated'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='position',
            field=models.CharField(choices=[('Main', 'Main Adviser'), ('Assistant', 'Assistant Adviser')], default='Main', max_length=50, verbose_name='Adviser Position'),
        ),
    ]
