# Generated by Django 5.2.1 on 2025-11-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0040_remove_adviser_is_active_adviser_date_deactivated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='academic_year',
            field=models.CharField(blank=True, help_text='The academic year of service (e.g., 2024-2025)', max_length=10, null=True, verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='officer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this officer currently active? (Uncheck this for past officers)', verbose_name='Currently Active'),
        ),
    ]
