# Generated by Django 5.2.1 on 2025-11-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0041_officer_academic_year_officer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateform',
            name='alumniID',
        ),
        migrations.AddField(
            model_name='graduateform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('clinic_admin', 'Clinic Admin'), ('guidance', 'Guidance'), ('org_admin', 'Org Admin'), ('guard', 'Guard'), ('student', 'Student'), ('staff', 'Staff'), ('discipline_officer', 'Discipline Officer'), ('alumni_officer', 'Alumni Officer'), ('student_life_staff', 'Student Life Staff')], default='student', max_length=20),
        ),
    ]
