# Generated by Django 5.2.1 on 2025-11-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0042_remove_graduateform_alumniid_graduateform_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateform',
            name='id',
        ),
        migrations.AddField(
            model_name='graduateform',
            name='graduateID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
