# Generated by Django 5.2.1 on 2025-11-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0043_remove_graduateform_id_graduateform_graduateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateform',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.studentinfo'),
        ),
    ]
