# Generated by Django 5.2.1 on 2025-11-08 02:17

import django.db.models.deletion
import mainpage.models.studentorg
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0044_alter_graduateform_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCBL',
            fields=[
                ('cbl_id', models.AutoField(primary_key=True, serialize=False)),
                ('cbl_file', models.FileField(upload_to='organization_cbls/', validators=[mainpage.models.studentorg.validate_file_extension], verbose_name='Constitution and By-Laws File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the currently active CBL for the organization?')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbl_documents', to='mainpage.organization')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
