# Generated by Django 5.2.1 on 2025-11-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0045_organizationcbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling_schedule',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_schedule_set', to='mainpage.caseprofile'),
        ),
    ]
