# Generated by Django 5.2.1 on 2025-11-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0048_alter_studentinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyhealthassistancerecord',
            name='name',
        ),
        migrations.AlterField(
            model_name='medicalrequirement',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.staffinfo'),
        ),
        migrations.AlterField(
            model_name='mentalhealthrecord',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.staffinfo'),
        ),
    ]
