# Generated by Django 5.2.1 on 2025-11-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0049_remove_emergencyhealthassistancerecord_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyhealthassistancerecord',
            name='date_assisted',
            field=models.DateField(),
        ),
    ]
