# Generated by Django 5.2.1 on 2025-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0050_alter_emergencyhealthassistancerecord_date_assisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionrecord',
            name='name',
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='date_prescribed',
            field=models.DateField(),
        ),
    ]
