# Generated by Django 5.2.1 on 2025-11-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0051_remove_prescriptionrecord_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exit_interview_db',
            name='emailadd',
        ),
    ]
