# Generated by Django 5.2.1 on 2025-11-14 14:43

import mainpage.models.guidance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0052_remove_exit_interview_db_emailadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtassessment',
            name='scheduled_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ojtassessment',
            name='schoolYear',
            field=models.CharField(default=mainpage.models.guidance.get_current_school_year, max_length=9),
        ),
    ]
