# Generated by Django 5.2.1 on 2025-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0053_ojtassessment_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtassessment',
            name='dateRecieved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
