# Generated by Django 5.2.1 on 2025-11-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0054_alter_ojtassessment_daterecieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='program',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='venue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
