# Generated by Django 5.2.1 on 2025-11-16 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0055_rename_date_time_program_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
