# Generated by Django 5.2.1 on 2025-11-23 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0056_mod_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('clinic_admin', 'Clinic Admin'), ('guidance', 'Guidance'), ('org_admin', 'Org Admin'), ('guard', 'Guard'), ('student', 'Student'), ('staff', 'Staff'), ('discipline_officer', 'Discipline Officer'), ('alumni_officer', 'Alumni Officer'), ('student_life_staff', 'Student Life Staff')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
