# Generated by Django 5.2.1 on 2025-11-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0057_temporaryuser_role_alter_temporaryuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='action_taken',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Oral Reprimand', 'Oral Reprimand'), ('Written Reprimand', 'Written Reprimand'), ('Community Service', 'Community Service'), ('Suspension', 'Suspension'), ('Expulsion', 'Expulsion'), ('Counseling', 'Counseling/Intervention'), ('Others', 'Other Action/Penalty')], default='Pending Review', max_length=50, verbose_name='Action Taken'),
        ),
    ]
